### ISSUE TITLE
Incoming video stream of remote participants not available

### ISSUE THREAD

**Issue by pepijnverburg** [whereby/browser-sdk#72] opened 2023-09-22 15:18 UTC
Hi there,

First of all thank you for the work for this early version of the SDK. The flexibility introduced with it was the key factor for us to choose Whereby. We have been implementing the SDK in NextJS over the past few weeks and all is running smoothly with setting up the connection. However, we noticed that the video streams of other participants than the local one cannot be retrieved. We properly get the remote participants, but the stream is always empty.

Any pointers how to solve this?

SDK version: 2.0.0-alpha20

Logged remote participant:
<img width="539" alt="Screenshot 2023-09-22 at 17 15 00" src="https://github.com/whereby/browser-sdk/assets/15874104/a8a55298-aa86-4f3a-b450-2026c75e7280">

Our rendering:
```jsx
{remoteParticipants.map((participant, i) => {
    if (!participant) {
        return null;
    }

    return (
        <motion.div
            key={participant.id}
            className={classNames(
                'flex-grow flex-shrink min-w-0',
                variant === 'compact' && 'relative',
                variant === 'spacious' && 'aspect-square rounded overflow-hidden bg-gray-100 w-[52%] absolute border',
                i === 0 && variant === 'spacious' && 'right-0 top-0 z-10',
                i === 1 && variant === 'spacious' && 'left-0 bottom-0',
            )}
            variants={defaultFadeInVariants}
            initial="hidden"
            animate="visible"
        >
            {participant.stream && (
                <VideoView
                    stream={participant.stream}
                    style={{ width: "100%", height: "100%", objectFit: "cover" }}
                />
            )}
            <div
                className={classNames(
                    `absolute bottom-2 backdrop-blur-lg p-2 flex justify-center rounded gap-4 bg-gray-800/90 text-white z-20`,
                    variant === 'spacious' && 'left-2',
                    i === 0 && variant === 'compact' && 'left-2',
                    i > 0 && variant === 'compact' && 'right-2',
                )}
            >
                <span>{participant.displayName || 'Guest'}</span>
            </div>
        </motion.div>
    );
})}
```

**Comment by havardholvik** [comment] 2023-09-25 07:36
Hi there 👋  Excited to hear you have started playing around with our new SDK. 

I have now done some testing on my end, and I can reproduce your issue. There seems to be a regression when using rooms in "normal" mode. We will look at a fix straight away.

Meanwhile, could you try creating your rooms in "group" mode. This should work, and might unblock you while waiting for a fix 🤞

**Comment by pepijnverburg** [comment] 2023-09-27 17:30
Thanks for the quick reply @havardholvik! Good to hear you can reproduce it in your environment as well. Setting the room mode to group has worked for us. We'll use that in the mean time. Again great work on the SDK and curious to see how it develops. Will keep this issue open for tracking purposes.

**Comment by havardholvik** [comment] 2023-10-09 10:52
@pepijnverburg : This issue should be fixed now in @whereby.com/browser-sdk@2.0.0-alpha22

**Closed by havardholvik** 2023-10-09 10:52 UTC
Labels: bug
